@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDllYTE0OWQ3N2UxZTBiMjMyNmIwYSIsImlhdCI6MTc0NTkxNjk0OCwiZXhwIjoxNzQ1OTIwNTQ4fQ.Q3VNFmXNLdta6h4xvDXB81wwUxQ9i3qqgzc6cTLJVco

### Crear albarán (simple o múltiple)
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": "6809eabc9d77e1e0b2326b1b",
  "type": "hours",
  "entries": [
    {
      "type": "hour",
      "description": "Montaje inicial",
      "quantity": 5,
      "unit": "hours"
    },
    {
      "type": "hour",
      "description": "Operario 2",
      "quantity": 8,
      "unit": "hours"
    }
  ]
}

### Listar todos los albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}

### Mostrar albarán por ID
GET http://localhost:3000/api/deliverynote/6809ecb2eafd31f8779aab5c
Authorization: Bearer {{token}}

### Crear albarán (simple o múltiple)
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": "6809eabc9d77e1e0b2326b1b",
  "type": "hours",
  "entries": [
    {
      "description": "Montaje inicial",
      "quantity": 5,
      "unit": "hours"
    },
    {
      "description": "Operario 2",
      "quantity": 8,
      "unit": "hours"
    }
  ]
}

### Obtener albarán en PDF
GET http://localhost:3000/api/deliverynote/pdf/6809ecb2eafd31f8779aab5c
Authorization: Bearer {{token}}
Accept: application/pdf