@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MThiYWRhYmMwNzkyNjdiZjU0OTc5ZCIsImlhdCI6MTc0NjQ2MTQ4MCwiZXhwIjoxNzQ2NDY1MDgwfQ.KdNRL3fbyXKn30HfOnduBSzK6vhwmteJpjQn-rJl5Kw

### Crear albarán (simple o múltiple)
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": "6809eabc9d77e1e0b2326b1b",
  "type": "hours",
  "entries": [
    {
      "type": "hour",
      "description": "Montaje final3",
      "quantity": 5,
      "unit": "hours"
    },
    {
      "type": "hour",
      "description": "Operario 4",
      "quantity": 8,
      "unit": "hours"
    }
  ]
}

### Listar todos los albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}

### Mostrar albarán por ID
GET http://localhost:3000/api/deliverynote/6809ecb2eafd31f8779aab5c
Authorization: Bearer {{token}}

### Crear albarán (simple o múltiple)
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": "6809eabc9d77e1e0b2326b1b",
  "type": "hours",
  "entries": [
    {
      "description": "Montaje final",
      "quantity": 5,
      "unit": "hours"
    },
    {
      "description": "Operario 3",
      "quantity": 8,
      "unit": "hours"
    }
  ]
}

### Obtener albarán en PDF
GET http://localhost:3000/api/deliverynote/pdf/6818bb12bc079267bf5497a3
Authorization: Bearer {{token}}
Accept: application/pdf

### Firmar albarán (subir imagen a IPFS)
PATCH http://localhost:3000/api/deliverynote/sign/6818daa3ba267bdc0ec0dfcf
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="signature"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--MyBoundary--

### Paso 7: Borrar albarán (solo si no está firmado)
DELETE http://localhost:3000/api/deliverynote/6818e33aaf6c43da6e0c4433
Authorization: Bearer {{token}}

