### Registro (paso 1)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "gonzaloo@mail.com",
  "password": "12345678"
}

### Validar email (Paso 2)
PUT http://localhost:3000/api/user/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDI3MTI5MiwiZXhwIjoxNzQ0Mjc0ODkyfQ.pSMKDAj8NwZitIPv1zB7gSHiFpZGNIoFmSwlBigXUHE
Content-Type: application/json

{
  "code": "224511"
}

### Login (Paso 3)
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "gonzaloo@mail.com",
  "password": "12345678"
}

### Actualizar datos personales (Paso 4.1)
PUT http://localhost:3000/api/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDI3MTM3OSwiZXhwIjoxNzQ0Mjc0OTc5fQ.iWGPu6Bh9XpAsGhi16bG6HW1h-IhQwimZ9q6Zyyd1No
Content-Type: application/json

{
  "name": "Gonzalo",
  "lastname": "Montero Sierra",
  "nif": "12345678A"
}

### Actualizar datos compañía (Paso 4.2)
PATCH http://localhost:3000/api/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDI3MTM3OSwiZXhwIjoxNzQ0Mjc0OTc5fQ.iWGPu6Bh9XpAsGhi16bG6HW1h-IhQwimZ9q6Zyyd1No
Content-Type: application/json

{
  "name": "Mi Empresa S.L.",
  "cif": "B12345678",
  "address": "Calle Empresa 42",
  "isFreelancer": false
}


### Subir logo (Paso 5)
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzQxMzQyNywiZXhwIjoxNzQzNDE3MDI3fQ.gaJDFAaOb9hziegw0baqbeXmPLSEQ0tnKXz-wDPm9PY
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./storage/logo/logo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET user (paso 6.1)
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzQxNzU2NiwiZXhwIjoxNzQzNDIxMTY2fQ.ms8G0A7AL1l20I-othbqdTjpoDl5P_nI-r2aA8Nue_s

### DELETE soft
DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzQxNzU2NiwiZXhwIjoxNzQzNDIxMTY2fQ.ms8G0A7AL1l20I-othbqdTjpoDl5P_nI-r2aA8Nue_s

### DELETE hard
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzQxNzU2NiwiZXhwIjoxNzQzNDIxMTY2fQ.ms8G0A7AL1l20I-othbqdTjpoDl5P_nI-r2aA8Nue_s

### Crear cliente
POST http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDI3MjA5MCwiZXhwIjoxNzQ0Mjc1NjkwfQ.pl5tOB06iCVNmPWKynMjGIsTNhMc4jpNgqvVmRfs9T4
Content-Type: application/json

{
  "name": "Mi Empresa S.L.",
  "email": "gonzalooms@mail.com",
  "phone": "666777888",
  "address": "Calle Empresa 42"
}


### Actualizar un cliente existente (PUT)
PUT http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDI3MzA5OCwiZXhwIjoxNzQ0Mjc2Njk4fQ.vIFiQh5plPtWFUUOH1QHiRAcSXW2UUIvi2BjtYZ3puE
Content-Type: application/json

{
  "name": "Cliente Actualizado S.L.",
  "email": "clienteactualizado@mail.com",
  "phone": "999888777",
  "address": "Calle Nueva 99"
}

### Obtener todos los clientes
GET http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDcxNTYxNywiZXhwIjoxNzQ0NzE5MjE3fQ.j-mCjes51yEBYxKfNVx_Qi_8E5MxQUzkGY75KNJIdTg

### Obtener cliente por ID
GET http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDk2OTA2NiwiZXhwIjoxNzQ0OTcyNjY2fQ.rH8EFUDcBW_WWPApcNJNl5kJr-hn8svx72lGlxlZZsE

### Eliminar cliente (soft delete por defecto)
DELETE http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDcxNzg1OSwiZXhwIjoxNzQ0NzIxNDU5fQ.nNDM2bdqPmVwOgfgCr_IsoDGtH_zwU_4S4EiIcxQXOg

### Eliminar cliente permanentemente (hard delete)
DELETE http://localhost:3000/api/client/67f77af2791c8ec9246fadc5?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDcxNTYxNywiZXhwIjoxNzQ0NzE5MjE3fQ.j-mCjes51yEBYxKfNVx_Qi_8E5MxQUzkGY75KNJIdTg


### Listar clientes archivados
GET http://localhost:3000/api/client/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDcxODM3MSwiZXhwIjoxNzQ0NzIxOTcxfQ.Ra9I4EQs3zyCKbTrjygTkDsXiYojtLY6F4tX5T83qTo

### Recuperar cliente archivado
PATCH http://localhost:3000/api/client/recover/67f77af2791c8ec9246fadc5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDcxODM3MSwiZXhwIjoxNzQ0NzIxOTcxfQ.Ra9I4EQs3zyCKbTrjygTkDsXiYojtLY6F4tX5T83qTo

### Crear proyecto
POST http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NDk2OTE4OSwiZXhwIjoxNzQ0OTcyNzg5fQ.yIBjHaqoXAxNQ1pO-9ZWJ4YuwrbvbubbElCS1AJpWmg
Content-Type: application/json

{
  "name": "Proyecto Feria",
  "description": "Organización y montaje de la feria anual",
  "client": "67f77af2791c8ec9246fadc5"
}

### Actualizar proyecto existente
PUT http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQwNzEwMiwiZXhwIjoxNzQ1NDEwNzAyfQ.Iy75ynjdksmTLkzXF59jvakFqEFD2vjD2-8AQ-QSHMM
Content-Type: application/json

{
  "name": "Proyecto Feria (actualizado)",
  "description": "Feria 2025 en Sevilla",
  "client": "67f77af2791c8ec9246fadc5"
}

### Obtener todos los proyectos
GET http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQwNzUxOSwiZXhwIjoxNzQ1NDExMTE5fQ.iaPYb0a_hEC9zV_bROuvAh2H498XryVWYr_jfK3PEA0

### Obtener proyecto por ID
GET http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQwNzUxOSwiZXhwIjoxNzQ1NDExMTE5fQ.iaPYb0a_hEC9zV_bROuvAh2H498XryVWYr_jfK3PEA0

### Archivar proyecto (soft delete por defecto)
DELETE http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQwODczOCwiZXhwIjoxNzQ1NDEyMzM4fQ.o77ZFQ1iAayB98xesIRMBJPzKXT4wTjdcX88peK9cH8

### Eliminar proyecto (hard delete)
DELETE http://localhost:3000/api/project/68021dfd00b528e97145cb34?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQwODczOCwiZXhwIjoxNzQ1NDEyMzM4fQ.o77ZFQ1iAayB98xesIRMBJPzKXT4wTjdcX88peK9cH8

### Obtener proyectos archivados
GET http://localhost:3000/api/project/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQxMjc4MywiZXhwIjoxNzQ1NDE2MzgzfQ.vGrW_CoHNHDk4C5u2RqqmoF2eFYhNC_dLAjV7Vi3mZ4

### Recuperar proyecto archivado
PATCH http://localhost:3000/api/project/recover/68021dfd00b528e97145cb34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc3N2JjZWQ5YTY2NDVkOWUyZmM1MiIsImlhdCI6MTc0NTQxMjc4MywiZXhwIjoxNzQ1NDE2MzgzfQ.vGrW_CoHNHDk4C5u2RqqmoF2eFYhNC_dLAjV7Vi3mZ4
