### Registro (paso 1)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "gonzalooo@mail.com",
  "password": "12345678"
}

### Validar email (Paso 2)
PUT http://localhost:3000/api/user/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzI1NDcwNiwiZXhwIjoxNzQzMjU4MzA2fQ.rYVfi4D1piZ0lo2f8Ngq_M7gh6LgGaGCM3xXiTZbYAk
Content-Type: application/json

{
  "code": "493013"
}

### Login (Paso 3)
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "gonzalooo@mail.com",
  "password": "12345678"
}

### Actualizar datos personales (Paso 4.1)
PUT http://localhost:3000/api/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzM0NzQxNiwiZXhwIjoxNzQzMzUxMDE2fQ.gxYaVtEq0XelqIOndaxTuBLqmWV2o_O-HImrUOWhSaY
Content-Type: application/json

{
  "name": "Gonzalo",
  "lastname": "Montero Sierra",
  "nif": "12345678A"
}
### Actualizar datos compañía (Paso 4.2)
PATCH http://localhost:3000/api/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdmNGIyMTUxNTQ3OTYzNjgyNWM1ZiIsImlhdCI6MTc0MzQxMzQyNywiZXhwIjoxNzQzNDE3MDI3fQ.gaJDFAaOb9hziegw0baqbeXmPLSEQ0tnKXz-wDPm9PY
Content-Type: application/json

{
  "name": "Mi Empresa S.L.",
  "cif": "B12345678",
  "address": "Calle Empresa 42",
  "isFreelancer": false
}


### Subir logo (Paso 5)
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./storage/logo/logo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
