@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDllYTE0OWQ3N2UxZTBiMjMyNmIwYSIsImlhdCI6MTc0NTQ4MjI5NSwiZXhwIjoxNzQ1NDg1ODk1fQ.MQha_6WfDtSl52e8pxpUzf8Jzfk1KbSHBmOdiHYSFuA


### Registro (paso 1)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "gonzaloo@mail.com",
  "password": "12345678"
}

### Validar email (Paso 2)
PUT http://localhost:3000/api/user/validate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "code": "930776"
}

### Login (Paso 3)
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "gonzaloo@mail.com",
  "password": "12345678"
}

### Actualizar datos personales (Paso 4.1)
PUT http://localhost:3000/api/user/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Gonzalo",
  "lastname": "Montero Sierra",
  "nif": "12345678A"
}

### Actualizar datos compañía (Paso 4.2)
PATCH http://localhost:3000/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Mi Empresa S.L.",
  "cif": "B12345678",
  "address": "Calle Empresa 42",
  "isFreelancer": false
}


### Subir logo (Paso 5)
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./storage/logo/logo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET user (paso 6.1)
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

### DELETE soft
DELETE http://localhost:3000/api/user
Authorization: Bearer {{token}}

### DELETE hard
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer {{token}}

### Crear cliente
POST http://localhost:3000/api/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Mi Empresa S.L.",
  "email": "gonzalooms@mail.com",
  "phone": "666777888",
  "address": "Calle Empresa 42"
}


### Actualizar un cliente existente (PUT)
PUT http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Actualizado S.L.",
  "email": "clienteactualizado@mail.com",
  "phone": "999888777",
  "address": "Calle Nueva 99"
}

### Obtener todos los clientes
GET http://localhost:3000/api/client
Authorization: Bearer {{token}}

### Obtener cliente por ID
GET http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer {{token}}

### Eliminar cliente (soft delete por defecto)
DELETE http://localhost:3000/api/client/67f77af2791c8ec9246fadc5
Authorization: Bearer {{token}}

### Eliminar cliente permanentemente (hard delete)
DELETE http://localhost:3000/api/client/67f77af2791c8ec9246fadc5?soft=false
Authorization: Bearer {{token}}


### Listar clientes archivados
GET http://localhost:3000/api/client/archived
Authorization: Bearer {{token}}

### Recuperar cliente archivado
PATCH http://localhost:3000/api/client/recover/67f77af2791c8ec9246fadc5
Authorization: Bearer {{token}}

### Crear proyecto
POST http://localhost:3000/api/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proyecto Feria",
  "description": "Organización y montaje de la feria anual",
  "client": "6809ea869d77e1e0b2326b15"
}

### Actualizar proyecto existente
PUT http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proyecto Feria (actualizado)",
  "description": "Feria 2025 en Sevilla",
  "client": "67f77af2791c8ec9246fadc5"
}

### Obtener todos los proyectos
GET http://localhost:3000/api/project
Authorization: Bearer {{token}}

### Obtener proyecto por ID
GET http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer {{token}}

### Archivar proyecto (soft delete por defecto)
DELETE http://localhost:3000/api/project/68021dfd00b528e97145cb34
Authorization: Bearer {{token}}

### Eliminar proyecto (hard delete)
DELETE http://localhost:3000/api/project/68021dfd00b528e97145cb34?soft=false
Authorization: Bearer {{token}}

### Obtener proyectos archivados
GET http://localhost:3000/api/project/archived
Authorization: Bearer {{token}}

### Recuperar proyecto archivado
PATCH http://localhost:3000/api/project/recover/68021dfd00b528e97145cb34
Authorization: Bearer {{token}}

### Crear albarán (simple o múltiple)
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project": "6809eabc9d77e1e0b2326b1b",
  "type": "hours",
  "entries": [
    {
      "type": "hour",
      "description": "Montaje inicial",
      "quantity": 5,
      "unit": "hours"
    },
    {
      "type": "hour",
      "description": "Operario 2",
      "quantity": 8,
      "unit": "hours"
    }
  ]
}

### Listar todos los albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}

### Mostrar albarán por ID
GET http://localhost:3000/api/deliverynote/6809ecb2eafd31f8779aab5c
Authorization: Bearer {{token}}
